"""
MOBABuildEnv — build-optimisation environment for MOBA games.

Episode structure
-----------------
The agent fills 6 generic item slots (ITEM_1 … ITEM_6) by selecting one item
per step from the candidate pool generated by :class:`MOBAGenerator`.

Role-based stat weights
------------------------
MOBA builds are highly role-dependent.  Three role presets are available:

    • "ad_carry"  — maximise attack_damage and attack_speed
    • "ap_mage"   — maximise ability_power and cooldown_reduction
    • "tank"      — maximise armor, magic_resistance, and health

The ``role`` argument selects the preset; ``stat_weights`` overrides completely.

Reward
------
Dense delta reward: improvement in build score per step.  Score combines
weighted stats, slot-fill bonus (6 slots → full build), and rarity.
"""

from __future__ import annotations

from typing import Dict, List, Literal, Optional, Union

import torch
from tensordict import TensorDict

from envs.base import BuildEnvBase
from envs.generators import MOBAGenerator

_ROLE_WEIGHTS: Dict[str, Dict[str, float]] = {
    "ad_carry": {
        "attack_damage": 1.5,
        "ability_power": 0.2,
        "armor": 0.3,
        "magic_resistance": 0.3,
        "health": 0.5,
        "mana": 0.2,
        "cooldown_reduction": 0.4,
        "attack_speed": 1.2,
    },
    "ap_mage": {
        "attack_damage": 0.2,
        "ability_power": 1.5,
        "armor": 0.3,
        "magic_resistance": 0.4,
        "health": 0.4,
        "mana": 0.8,
        "cooldown_reduction": 1.2,
        "attack_speed": 0.1,
    },
    "tank": {
        "attack_damage": 0.3,
        "ability_power": 0.2,
        "armor": 1.3,
        "magic_resistance": 1.3,
        "health": 1.5,
        "mana": 0.3,
        "cooldown_reduction": 0.6,
        "attack_speed": 0.1,
    },
    "support": {
        "attack_damage": 0.2,
        "ability_power": 0.9,
        "armor": 0.7,
        "magic_resistance": 0.7,
        "health": 0.8,
        "mana": 1.0,
        "cooldown_reduction": 1.1,
        "attack_speed": 0.2,
    },
}


class MOBABuildEnv(BuildEnvBase):
    """
    Sequential build-optimisation environment for MOBA games.

    Observation space (TensorDict keys)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    items           [B, N, 8]  — normalised item stat features
    costs           [B, N]     — item gold costs
    slot_ids        [B, N]     — item slot index (0–5)
    rarities        [B, N]     — rarity multiplier per item
    budget          [B]        — total gold budget
    equipped        [B, N]     — bool mask of purchased items
    slot_filled     [B, 6]     — bool mask of filled item slots
    budget_remaining[B]        — remaining gold
    current_score   [B]        — running build score
    action_mask     [B, N]     — valid item selections
    """

    NAME = "moba"
    name: str = "moba"
    stat_names: List[str] = [
        "attack_damage", "ability_power", "armor", "magic_resistance",
        "health", "mana", "cooldown_reduction", "attack_speed",
    ]
    num_slots: int = 6

    def __init__(
        self,
        generator: Optional[MOBAGenerator] = None,
        generator_params: Optional[dict] = None,
        role: Literal["ad_carry", "ap_mage", "tank", "support"] = "ad_carry",
        stat_weights: Optional[Dict[str, float]] = None,
        slot_bonus: float = 6.0,
        rarity_bonus: float = 3.0,
        device: Union[str, torch.device] = "cpu",
        **kwargs,
    ):
        """
        Args:
            role:         Preset role that selects default stat weights.
                          Ignored when ``stat_weights`` is given explicitly.
            stat_weights: Override per-stat reward multipliers.
        """
        generator_params = generator_params or {}
        if generator is None:
            generator = MOBAGenerator(device=device, **generator_params)

        resolved_weights = stat_weights or _ROLE_WEIGHTS.get(role, _ROLE_WEIGHTS["ad_carry"])

        super().__init__(
            generator=generator,
            generator_params=generator_params,
            stat_weights=resolved_weights,
            slot_bonus=slot_bonus,
            rarity_bonus=rarity_bonus,
            device=device,
            **kwargs,
        )
        self.role = role

    def _reset_instance(self, tensordict: TensorDict) -> TensorDict:
        if "equipped" in tensordict.keys():
            return tensordict

        bs = tensordict.batch_size
        N = tensordict["items"].shape[1]
        device = tensordict.device

        tensordict["equipped"] = torch.zeros(*bs, N, dtype=torch.bool, device=device)
        tensordict["slot_filled"] = torch.zeros(*bs, self.num_slots, dtype=torch.bool, device=device)
        tensordict["budget_remaining"] = tensordict["budget"].clone()
        tensordict["current_score"] = torch.zeros(*bs, device=device)
        tensordict["prev_score"] = torch.zeros(*bs, device=device)
        return tensordict

    def _get_action_mask(self, tensordict: TensorDict) -> torch.Tensor:
        equipped = tensordict["equipped"]
        slot_filled = tensordict["slot_filled"]
        budget_remaining = tensordict["budget_remaining"]
        costs = tensordict["costs"]
        slot_ids = tensordict["slot_ids"]

        mask = ~equipped
        slot_blocked = slot_filled.gather(1, slot_ids.long())
        mask = mask & ~slot_blocked
        mask = mask & (costs <= budget_remaining.unsqueeze(-1))
        return mask

    def _get_reward(self, tensordict: TensorDict, actions: Optional[torch.Tensor] = None) -> torch.Tensor:
        return tensordict["current_score"] - tensordict["prev_score"]

    def __repr__(self) -> str:
        return f"MOBABuildEnv(role={self.role}, device={self.device})"
