"""
RPGBuildEnv — build-optimisation environment for fantasy RPGs.

Episode structure
-----------------
The agent fills 10 equipment slots (weapon, helmet, chest, gloves, boots,
ring×2, amulet, accessory×2) by selecting one item per step from the
candidate pool generated by :class:`RPGGenerator`.

Reward
------
Dense delta reward: at each step the agent receives the *improvement* in build
score caused by equipping the selected item.  The total cumulative reward equals
the final build score, which combines:

    • Weighted stat sum (RPG-specific weights: critical_rate valued highest)
    • Slot-fill bonus (encourages completing the full build)
    • Rarity bonus (legendary > epic > … > common)

Action mask
-----------
An item is valid iff:
    (a) it is not already equipped,
    (b) its slot is not yet filled,
    (c) its cost does not exceed the remaining budget.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Union

import torch
from tensordict import TensorDict

from envs.base import BuildEnvBase
from envs.generators import RPGGenerator


class RPGBuildEnv(BuildEnvBase):
    """
    Sequential build-optimisation environment for fantasy RPG games.

    Observation space (TensorDict keys)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    items           [B, N, 7]  — normalised item stat features
    costs           [B, N]     — item acquisition costs
    slot_ids        [B, N]     — equipment slot index per item (0–9)
    rarities        [B, N]     — rarity multiplier per item
    budget          [B]        — total available budget
    equipped        [B, N]     — bool mask of currently equipped items
    slot_filled     [B, 10]    — bool mask of filled equipment slots
    budget_remaining[B]        — remaining budget after equips so far
    current_score   [B]        — running build score (used for reward delta)
    action_mask     [B, N]     — valid item selections
    """

    NAME = "rpg"
    name: str = "rpg"
    stat_names: List[str] = [
        "attack", "defense", "magic_power", "health",
        "speed", "critical_rate", "critical_damage",
    ]
    num_slots: int = 10

    # Default RPG stat weights (critical_rate valued highest — mirrors ScoringConfig)
    DEFAULT_STAT_WEIGHTS: Dict[str, float] = {
        "attack": 1.0,
        "defense": 0.8,
        "magic_power": 0.9,
        "health": 0.7,
        "speed": 0.6,
        "critical_rate": 1.2,
        "critical_damage": 1.0,
    }

    def __init__(
        self,
        generator: Optional[RPGGenerator] = None,
        generator_params: Optional[dict] = None,
        stat_weights: Optional[Dict[str, float]] = None,
        slot_bonus: float = 5.0,
        rarity_bonus: float = 2.0,
        device: Union[str, torch.device] = "cpu",
        **kwargs,
    ):
        generator_params = generator_params or {}
        if generator is None:
            generator = RPGGenerator(device=device, **generator_params)

        super().__init__(
            generator=generator,
            generator_params=generator_params,
            stat_weights=stat_weights or self.DEFAULT_STAT_WEIGHTS,
            slot_bonus=slot_bonus,
            rarity_bonus=rarity_bonus,
            device=device,
            **kwargs,
        )

    # ------------------------------------------------------------------
    # Abstract method implementations
    # ------------------------------------------------------------------

    def _reset_instance(self, tensordict: TensorDict) -> TensorDict:
        """Initialise episode state from a freshly generated (or provided) instance."""
        if "equipped" in tensordict.keys():
            # Already initialised — e.g. transductive search restart
            return tensordict

        bs = tensordict.batch_size
        N = tensordict["items"].shape[1]
        device = tensordict.device

        tensordict["equipped"] = torch.zeros(*bs, N, dtype=torch.bool, device=device)
        tensordict["slot_filled"] = torch.zeros(*bs, self.num_slots, dtype=torch.bool, device=device)
        tensordict["budget_remaining"] = tensordict["budget"].clone()
        tensordict["current_score"] = torch.zeros(*bs, device=device)
        tensordict["prev_score"] = torch.zeros(*bs, device=device)
        return tensordict

    def _get_action_mask(self, tensordict: TensorDict) -> torch.Tensor:
        """
        Return valid item mask [B, N].

        An item is valid iff it is unequipped, its slot is empty, and it
        is affordable within the remaining budget.
        """
        equipped = tensordict["equipped"]                  # [B, N] bool
        slot_filled = tensordict["slot_filled"]            # [B, 10] bool
        budget_remaining = tensordict["budget_remaining"]  # [B]
        costs = tensordict["costs"]                        # [B, N]
        slot_ids = tensordict["slot_ids"]                  # [B, N]

        # (a) Not already equipped
        mask = ~equipped  # [B, N]

        # (b) Slot not yet filled — gather slot_filled value for each item's slot
        slot_blocked = slot_filled.gather(1, slot_ids.long())  # [B, N]
        mask = mask & ~slot_blocked

        # (c) Affordable
        affordable = costs <= budget_remaining.unsqueeze(-1)  # [B, N]
        mask = mask & affordable

        return mask

    def _get_reward(self, tensordict: TensorDict, actions: Optional[torch.Tensor] = None) -> torch.Tensor:
        """Dense delta reward: improvement in build score this step."""
        return tensordict["current_score"] - tensordict["prev_score"]
