"""
FPSBuildEnv — build-optimisation environment for tactical FPS games.

Episode structure
-----------------
The agent fills 8 loadout slots (primary weapon, secondary weapon, helmet,
vest, gloves, boots, tactical, lethal) by selecting one item per step from the
candidate pool generated by :class:`FPSGenerator`.

Stat weights
------------
Damage and accuracy are weighted highest, reflecting the core FPS loop.
Mobility matters for run-and-gun playstyles; recoil_control helps sustained
accuracy.  Magazine size and reload_speed matter for suppression.

Reward
------
Dense delta reward: improvement in build score per step.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Union

import torch
from tensordict import TensorDict

from envs.base import BuildEnvBase
from envs.generators import FPSGenerator


class FPSBuildEnv(BuildEnvBase):
    """
    Sequential build-optimisation environment for tactical FPS loadouts.

    Observation space (TensorDict keys)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    items           [B, N, 7]  — normalised item stat features
    costs           [B, N]     — item costs (in-game currency)
    slot_ids        [B, N]     — loadout slot index per item (0–7)
    rarities        [B, N]     — rarity multiplier per item
    budget          [B]        — total currency budget
    equipped        [B, N]     — bool mask of selected items
    slot_filled     [B, 8]     — bool mask of filled loadout slots
    budget_remaining[B]        — remaining currency
    current_score   [B]        — running build score
    action_mask     [B, N]     — valid item selections
    """

    NAME = "fps"
    name: str = "fps"
    stat_names: List[str] = [
        "damage", "accuracy", "range", "mobility",
        "reload_speed", "recoil_control", "magazine_size",
    ]
    num_slots: int = 8

    DEFAULT_STAT_WEIGHTS: Dict[str, float] = {
        "damage": 1.2,
        "accuracy": 1.1,
        "range": 0.8,
        "mobility": 0.9,
        "reload_speed": 0.7,
        "recoil_control": 0.8,
        "magazine_size": 0.5,
    }

    def __init__(
        self,
        generator: Optional[FPSGenerator] = None,
        generator_params: Optional[dict] = None,
        stat_weights: Optional[Dict[str, float]] = None,
        slot_bonus: float = 4.0,
        rarity_bonus: float = 1.5,
        device: Union[str, torch.device] = "cpu",
        **kwargs,
    ):
        generator_params = generator_params or {}
        if generator is None:
            generator = FPSGenerator(device=device, **generator_params)

        super().__init__(
            generator=generator,
            generator_params=generator_params,
            stat_weights=stat_weights or self.DEFAULT_STAT_WEIGHTS,
            slot_bonus=slot_bonus,
            rarity_bonus=rarity_bonus,
            device=device,
            **kwargs,
        )

    def _reset_instance(self, tensordict: TensorDict) -> TensorDict:
        if "equipped" in tensordict.keys():
            return tensordict

        bs = tensordict.batch_size
        N = tensordict["items"].shape[1]
        device = tensordict.device

        tensordict["equipped"] = torch.zeros(*bs, N, dtype=torch.bool, device=device)
        tensordict["slot_filled"] = torch.zeros(*bs, self.num_slots, dtype=torch.bool, device=device)
        tensordict["budget_remaining"] = tensordict["budget"].clone()
        tensordict["current_score"] = torch.zeros(*bs, device=device)
        tensordict["prev_score"] = torch.zeros(*bs, device=device)
        return tensordict

    def _get_action_mask(self, tensordict: TensorDict) -> torch.Tensor:
        equipped = tensordict["equipped"]
        slot_filled = tensordict["slot_filled"]
        budget_remaining = tensordict["budget_remaining"]
        costs = tensordict["costs"]
        slot_ids = tensordict["slot_ids"]

        mask = ~equipped
        slot_blocked = slot_filled.gather(1, slot_ids.long())
        mask = mask & ~slot_blocked
        mask = mask & (costs <= budget_remaining.unsqueeze(-1))
        return mask

    def _get_reward(self, tensordict: TensorDict, actions: Optional[torch.Tensor] = None) -> torch.Tensor:
        return tensordict["current_score"] - tensordict["prev_score"]
